In [1]:
import simuOpt
simuOpt.setOptions(alleleType='short', optimized=True, quiet=True, numThreads=4)
import simuPOP as sim
import numpy as np
import pandas as pd
import h5py
from saegus import analyze

In [2]:
np.set_printoptions(precision=3, suppress=True)

In [15]:
trait = h5py.File('example_trait_data.hdf5')

In [16]:
allele_effects = np.array(trait['allele/effects'])

In [17]:
qtl = np.array(trait['qtl'])

In [18]:
qtl

array([  425,  4144,  6564,  6912,  8943,  9326, 11437, 11480, 13064,
       16309, 18787, 22171, 23093, 28903, 34913, 35493, 38448, 43071,
       43499, 44043])

In [19]:
allele_effects[qtl]

array([[   425.   ,      1.   ,      0.5  ,      3.   ,      1.478],
       [  4144.   ,      1.   ,      1.247,      2.   ,      1.602],
       [  6564.   ,      1.   ,      0.753,      3.   ,      0.578],
       [  6912.   ,      1.   ,      0.339,      3.   ,      0.011],
       [  8943.   ,      1.   ,      0.521,      3.   ,      0.085],
       [  9326.   ,      1.   ,      1.031,      3.   ,      2.298],
       [ 11437.   ,      1.   ,      2.155,      3.   ,      2.336],
       [ 11480.   ,      1.   ,      1.291,      3.   ,      2.774],
       [ 13064.   ,      1.   ,      0.287,      2.   ,      0.527],
       [ 16309.   ,      1.   ,      0.911,      3.   ,      0.5  ],
       [ 18787.   ,      1.   ,      1.05 ,      3.   ,      3.014],
       [ 22171.   ,      1.   ,      0.213,      3.   ,      0.786],
       [ 23093.   ,      1.   ,      1.551,      3.   ,      2.961],
       [ 28903.   ,      1.   ,      3.625,      3.   ,      1.119],
       [ 34913.   ,      1.   ,   

In [ ]:
super_table = analyze.tassel_results_tables(input_file_prefix+'example_2.txt', 
                                            input_file_prefix+'example_q_values.txt',
                                            mafrqs, qtad)

In [3]:
gwas_results = pd.read_csv('/home/vakanas/tassel-5-standalone/example_2.txt', sep='\t', index_col=0)

In [7]:
example_pop = sim.loadPopulation('example_pop.pop')

In [9]:
sim.stat(example_pop, numOfSegSites=sim.ALL_AVAIL, vars=['numOfSegSites', 'segSites'])

In [11]:
seg_loci = np.array(example_pop.dvars().segSites)

In [26]:
seg_loci.dtype

dtype('int64')

In [24]:
markers = np.array(np.array(gwas_results.Marker)[1:], dtype=np.int_)

In [33]:
markers

array([    0,     1,     2, ..., 44442, 44443, 44444])

In [37]:
sum(gwas_results.add_p < 0.05)

1463

In [38]:
qvals = pd.read_csv("/home/vakanas/tassel-5-standalone/example_q_values.txt", sep="\t", index_col=0)

In [43]:
qvals

q
1      0.993609
2      0.993609
3      0.997369
4      0.993609
5      0.993609
6      0.993609
7      0.996347
8      0.993609
9      0.993609
10     0.993609
11     0.997512
12     0.997512
13     0.995169
14     0.997512
15     0.993609
16     0.993609
17     0.993609
18     0.993609
19     0.993609
20     0.997512
21     0.993609
22     0.993609
23     0.993609
24     0.997512
25     0.993609
26     0.993609
27     0.993609
28     0.993609
29     0.993609
30     0.995337
...         ...
42808  0.993609
42809  0.993609
42810  0.993609
42811  0.993609
42812  0.993609
42813  0.995865
42814  0.993609
42815  0.993609
42816  0.993609
42817  0.993609
42818  0.993609
42819  0.993609
42820  0.993609
42821  0.993609
42822  0.993609
42823  0.993609
42824  0.993609
42825  0.993609
42826  0.993609
42827  0.993609
42828  0.993609
42829  0.993609
42830  0.993609
42831  0.993609
42832  0.993609
42833  0.993609
42834  0.993609
42835  0.993609
42836  0.993609
42837  0.993609

[42837 rows x 1 columns]